---
- name: Testing awx playbook.
  hosts: localhost
  gather_facts: false
  become: true
  
  vars:
    extra_vars: "This is testing for vars"

  tasks:
    - name: Testing
      command: echo "welcome to AWX Tower"
      register: test

    - name: debug the test
      debug:
        msg: "{{ test.stdout_lines }}"  

    - name: Debug the vars
      debug:
        msg: "{{ vars }}"
