---
- name: Testing awx playbook.
  hosts: localhost
  gather_facts: true
  become: true

  vars:
    extra_vars: "Hello World"

  tasks:
    - name: Testing
      command: echo "welcome to AWX Tower"
      register: test

    - name: debug the test
      debug:
        msg: "{{ test.stdout_lines }}"  

    - name: "Ansible | Print a variable"
      debug:
        msg: "{{ vars }}"
